# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.disksize.size = "20GB"
  config.vm.provider "virtualbox" do |vb|  
    vb.name = "ubuntu docker"
    vb.memory = 8192
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.provision "shell", path: ".\\scripts\\bootstrap.sh"

end
