# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  os = "ubuntu/trusty64"
  net_ip = "192.168.55"

  config.vm.box = "ubuntu/trusty64"

  config.disksize.size = "#{os}"
  config.vm.provider "virtualbox" do |vb|  
    vb.name = "ubuntu docker"
    vb.memory = 8192
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

  config.vm.network "forwarded_port", guest: 4000, host: 4000

  config.vm.provision "file", source: "./data/app/app.py", destination: "/home/vagrant/workspace/app.py"
  config.vm.provision "file", source: "./data/app/requirements.txt", destination: "/home/vagrant/workspace/requirements.txt"
  config.vm.provision "file", source: "./data/docker/Dockerfile", destination: "/home/vagrant/workspace/Dockerfile"
  config.vm.provision "file", source: "./data/docker/docker-compose.yml", destination: "/home/vagrant/workspace/docker-compose.yml"
  config.vm.provision "shell", path: ".\\scripts\\bootstrap.sh"
  config.vm.provision "shell", path: ".\\scripts\\bootstrap_docker.sh"
  config.vm.provision "shell", path: ".\\scripts\\init_docker_app.sh"

end
